### PR TITLE
Persistent column hiding and detail prettification (no re-running required)

### LINKED ISSUE #8: Make sure the page adjustments persist for an entire V1 session
For example, right now, if you use the "Assign" menu on a card, the page is re-rendered on save and all of the hidden columns are back.

### PR DESCRIPTION
**Pull request by BaseCase**
:earth_asia::four_leaf_clover::pear:

This will close #8 
## TODO
- [x] persistent column hiding
- [x] persistent card details prettification

### CODE REVIEW

**Comment by BaseCase** [comment]
Huh, so I found a good way to persistently hide the columns using CSS, and I thought I'd be able to do the same thing for the epic cards, but no dice :(

The issue is that the only way to identify a card of a specific epic type is by attributes on a _child element_ of the actual `<div>` that is the card itself. In CSS, as far as I know, there's no way to select an element based on attributes of its children.

Anybody have any ideas how to approach this? Maybe there is some kind of event we can hook into to re-run the card removal JS? Or, a pretty gross approach would be to `setInterval` on the card removal JS and it'd always re-remove them if they reappear.

**Comment by bigtiger** [comment]
Maybe this? http://stackoverflow.com/questions/1014861/is-there-a-css-parent-selector

**Comment by BaseCase** [comment]
Decided to save persistent epic hiding for a future PR since this mostly works and that's a harder problem.

**Comment by bigtiger** [comment]
:+1:

**Pull request merged**
